// TODO: generated by `supabase gen types typescript --local > supabase/types.ts`
// Run: npx supabase gen types typescript --project-id <id> > supabase/types.ts

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
